run:
  timeout: 20m
  tests: true
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude:
    - "error-naming: error var invalidFileMode should have name of the form errFoo"
    - "var-naming: struct field"
    - "var-naming: don't use underscores in Go names"
    - "var-naming: func parameter"
    - "var-naming: don't use ALL_CAPS in Go names; use CamelCase"
    - "var-naming: method parameter"
    - "var-naming: type"
    - "unexported-return: exported func"

output:
  print-linter-name: true
  sort-results: true
  uniq-by-line: false
  print-issued-lines: true

linters:
  disable-all: true
  fast: false
  enable:
    # A stricter replacement for gofmt.
    - gofumpt
    # Inspects source code for security problems.
    - gosec
    # Check for correctness of programs.
    - govet
    # Drop-in replacement of golint.
    - revive
