#!/bin/bash

# Configuration file for goisilon tests

GOISILON_ENDPOINT="https://1.1.1.0:8080"
GOISILON_USERNAME="admin"
GOISILON_GROUP=""
GOISILON_PASSWORD="admin"
GOISILON_INSECURE="true"
GOISILON_VOLUMEPATH="/ifs/data/csi"
GOISILON_VOLUMEPATH_PERMISSIONS="0777"
GOISILON_AUTHTYPE=0
