// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/dell/goisilon/api"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// APIVersion provides a mock function with no fields
func (_m *Client) APIVersion() uint8 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIVersion")
	}

	var r0 uint8
	if rf, ok := ret.Get(0).(func() uint8); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint8)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, path, id, params, headers, resp
func (_m *Client) Delete(ctx context.Context, path string, id string, params api.OrderedValues, headers map[string]string, resp interface{}) error {
	ret := _m.Called(ctx, path, id, params, headers, resp)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, api.OrderedValues, map[string]string, interface{}) error); ok {
		r0 = rf(ctx, path, id, params, headers, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Do provides a mock function with given fields: ctx, method, path, id, params, body, resp
func (_m *Client) Do(ctx context.Context, method string, path string, id string, params api.OrderedValues, body interface{}, resp interface{}) error {
	ret := _m.Called(ctx, method, path, id, params, body, resp)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, api.OrderedValues, interface{}, interface{}) error); ok {
		r0 = rf(ctx, method, path, id, params, body, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DoWithHeaders provides a mock function with given fields: ctx, method, path, id, params, headers, body, resp
func (_m *Client) DoWithHeaders(ctx context.Context, method string, path string, id string, params api.OrderedValues, headers map[string]string, body interface{}, resp interface{}) error {
	ret := _m.Called(ctx, method, path, id, params, headers, body, resp)

	if len(ret) == 0 {
		panic("no return value specified for DoWithHeaders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, api.OrderedValues, map[string]string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, method, path, id, params, headers, body, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, path, id, params, headers, resp
func (_m *Client) Get(ctx context.Context, path string, id string, params api.OrderedValues, headers map[string]string, resp interface{}) error {
	ret := _m.Called(ctx, path, id, params, headers, resp)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, api.OrderedValues, map[string]string, interface{}) error); ok {
		r0 = rf(ctx, path, id, params, headers, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuthToken provides a mock function with no fields
func (_m *Client) GetAuthToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetCSRFToken provides a mock function with no fields
func (_m *Client) GetCSRFToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCSRFToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetReferer provides a mock function with no fields
func (_m *Client) GetReferer() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetReferer")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Group provides a mock function with no fields
func (_m *Client) Group() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Post provides a mock function with given fields: ctx, path, id, params, headers, body, resp
func (_m *Client) Post(ctx context.Context, path string, id string, params api.OrderedValues, headers map[string]string, body interface{}, resp interface{}) error {
	ret := _m.Called(ctx, path, id, params, headers, body, resp)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, api.OrderedValues, map[string]string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, path, id, params, headers, body, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Put provides a mock function with given fields: ctx, path, id, params, headers, body, resp
func (_m *Client) Put(ctx context.Context, path string, id string, params api.OrderedValues, headers map[string]string, body interface{}, resp interface{}) error {
	ret := _m.Called(ctx, path, id, params, headers, body, resp)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, api.OrderedValues, map[string]string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, path, id, params, headers, body, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAuthToken provides a mock function with given fields: token
func (_m *Client) SetAuthToken(token string) {
	_m.Called(token)
}

// SetCSRFToken provides a mock function with given fields: csrf
func (_m *Client) SetCSRFToken(csrf string) {
	_m.Called(csrf)
}

// SetReferer provides a mock function with given fields: referer
func (_m *Client) SetReferer(referer string) {
	_m.Called(referer)
}

// User provides a mock function with no fields
func (_m *Client) User() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// VolumePath provides a mock function with given fields: name
func (_m *Client) VolumePath(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for VolumePath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// VolumesPath provides a mock function with no fields
func (_m *Client) VolumesPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VolumesPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
